### ISSUE TITLE
Parallel download

### ISSUE THREAD

**Issue by 5hojib** [Mayuri-Chan/pyrofork#28]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/Mayuri-Chan/pyrofork/archive/master.zip` and reproduced the issue using the latest development version

### Description

In previous version like, 2.2.10 or less, it was download multiple file in parallel, but now, it's download one after one. I hope you will revert download function 

### Steps to reproduce

.

### Code example

```python
.
```

**Comment by yasirarism** [comment]
Set `max_concurrent_transmissions` in Client
