### ISSUE TITLE
message.photo  not working

### ISSUE THREAD

**Issue by TGxMATRIX** [Mayuri-Chan/pyrofork#33]
### Checklist

- [X] I am sure the error is coming from Pyrogram's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U https://github.com/Mayuri-Chan/pyrofork/archive/master.zip` and reproduced the issue using the latest development version

### Description

message.photo  not working

### Steps to reproduce

message.photo  not working

### Code example

```python
message.photo  not working
```

**Comment by wulan17** [comment]
Give logs and example code

**Comment by wulan17** [comment]
No respone for 3 weeks
so i mark this issue as resolved
