### ISSUE TITLE
tgcrypto-pyrofork unable to install on arm processor

### ISSUE THREAD

**Issue by gmankab** [Mayuri-Chan/pyrofork#71]
### Checklist

- [X] I am sure the error is coming from Pyrofork's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U git+https://github.com/Mayuri-Chan/pyrofork` and reproduced the issue using the latest development version

### Description

i have problem with installing tgcrypto-pyrofork

on x86 machines it installs without any issues

error on arm machines when try to install from pypi:
```shell
pip install tgcrypto-pyrofork
ERROR: Could not find a version that satisfies the requirement tgcrypto-pyrofork (from versions: none)
ERROR: No matching distribution found for tgcrypto-pyrofork
```

but it can be installed from git without any issues
```shell
pip install git+https://github.com/Mayuri-Chan/tgcrypto-pyrofork
Successfully installed TgCrypto-pyrofork-1.2.6
```

i tried to use fedora and ubuntu linux

### Steps to reproduce

run `pip install tgcrypto-pyrofork`

**Comment by wulan17** [comment]
![image](https://github.com/Mayuri-Chan/pyrofork/assets/18455603/c9309c0e-50a6-41e4-b718-5cfa6edb1858)
im uploaded the sourcecode to pypi
the problem sould be fixed now
i can't make whl for linux arm because i don't have linux server/device with arm arch

**Comment by gmankab** [comment]
thank you, it builds works now

if you want to publish arm binary builds, i can give you ssh access to my oracle cloud arm server

or you can youse qemu to emulate arm
