### ISSUE TITLE
type object is not subscriptable

### ISSUE THREAD

**Issue by kunodee** [Mayuri-Chan/pyrofork#95]
### Checklist

- [X] I am sure the error is coming from Pyrofork's code and not elsewhere
- [X] I have searched in the issue tracker for similar bug reports, including closed ones
- [X] I ran `pip3 install -U git+https://github.com/Mayuri-Chan/pyrofork` and reproduced the issue using the latest development version

### Description

![image](https://github.com/user-attachments/assets/7e95d669-5262-4ed1-a2cb-043127c607c5)

list is not support python 3.8 it must be List

### Steps to reproduce

1. Install python3.8
2. Import the lib ?

### Code example

```python
from pyrogram import Client

app = Client()

app.run()
```

**Comment by yasirarism** [comment]
Wait new update, it's typo. You can use test on staging branch
